In [1]:
print('hello world')  # ctrl + enter

hello world


In [1]:
import numpy as np 

In [4]:
# creating of an array 
arr = np.array([25,32,12,63,96,45])
arr 

array([25, 32, 12, 63, 96, 45])

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr.dtype

dtype('int32')

In [9]:
# creating of an array 
arr = np.array([25,32,12,63,96,45,52.2,'upflairs'])
arr 

array(['25', '32', '12', '63', '96', '45', '52.2', 'upflairs'],
      dtype='<U32')

In [8]:
arr.dtype

dtype('float64')

In [10]:
arr.ndim 

1

In [11]:
arr 

array(['25', '32', '12', '63', '96', '45', '52.2', 'upflairs'],
      dtype='<U32')

In [13]:
arr[-5]  # single item 

'63'

In [14]:
arr[3:6]  # multiple item 

array(['63', '96', '45'], dtype='<U32')

In [15]:
# arr[start:stoping:jump]    
arr[3:6:1]

array(['63', '96', '45'], dtype='<U32')

In [21]:
arr[::-1]  

array(['upflairs', '52.2', '45', '96', '63', '12', '32', '25'],
      dtype='<U32')

In [22]:
arr

array(['25', '32', '12', '63', '96', '45', '52.2', 'upflairs'],
      dtype='<U32')

In [24]:
arr[1] = 'aman'

In [28]:
arr = np.arange(25)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr2  = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr2.ndim 

2

In [33]:
arr2[-1]   #row single 

array([7, 8, 9])

In [36]:
arr2[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr = np.array([[[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]],[[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]],[[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]])

In [42]:
arr.ndim  

3

In [43]:
arr 

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [3]:
# 3D -->  
arr = np.zeros(5)
arr 

array([0., 0., 0., 0., 0.])

In [4]:
arr = np.zeros((5,4))
arr 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
arr = np.zeros((2,5,5))
arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [12]:
arr.shape  

(2, 5, 5)

In [13]:
arr = np.ones((5,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
arr = np.linspace(1,20,10)
arr 

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [17]:
import random 

In [25]:
random.randint(10,20)

11

In [26]:
random.random()  # by default it return in btwn 0 - 1 

0.32174013978917404

In [30]:
ls = ['gagan','aman','jyoti','tishika','harshit'] 
random.choice(ls) 

'jyoti'

In [61]:
ls = ['gagan','aman','jyoti','tishika','harshit'] 
random.choices(ls,k=2) 

['jyoti', 'aman']

In [62]:
ls = ['gagan','aman','jyoti','tishika','harshit'] 
random.shuffle(ls) 
ls 

['harshit', 'aman', 'jyoti', 'tishika', 'gagan']

In [75]:
# np.random.randint 
# np.random.random 
# np.random.shuffle
# np.random.choice 

arr = np.random.randint(1,50,10)
arr 

array([26, 34, 41, 18, 49, 20, 28, 16, 26,  4])

In [76]:
arr = np.random.randint(1,50,(10,5))
arr 

array([[27, 39, 16, 30, 40],
       [40, 28,  7,  2,  5],
       [23, 27, 29, 18, 42],
       [46, 36, 46, 39, 46],
       [ 9,  2, 20, 18,  4],
       [ 6, 20, 22,  5, 44],
       [26, 34, 26, 26, 47],
       [19, 23, 17, 24, 12],
       [46, 49, 18, 30, 25],
       [13, 14,  9, 12, 46]])

In [ ]:
# 100,200,  2, 5,4 

In [77]:
arr = np.random.randint(1,500,200)
arr 

# write a program using python to find out the no, of item that are less than or equal to 100

array([268, 198, 354, 256, 225, 394, 261, 394, 237,  26, 456, 323, 179,
        55, 450,  69, 272, 496,  61, 297, 491, 276,  95, 417, 132, 203,
       336, 256, 356,  96, 321,  11, 388, 480,  39, 369, 445, 385, 192,
        13, 309, 434, 414,  25, 463, 216, 317, 112, 480,  90, 150, 454,
        31,  75, 444, 493, 474, 374, 145, 178, 260, 472, 247, 475, 131,
       157, 342, 253, 257, 311, 494,  76, 205,  63, 353, 482,  27,  17,
       332, 204, 459, 254, 484, 308,  62,  93, 123, 476, 105, 445, 340,
       137, 133, 142, 348, 214, 202,  91, 424,   9, 244, 350, 256, 469,
       291, 243, 390,  76, 222, 109, 198, 208, 482, 253, 163,  80, 246,
       260, 141, 241, 176, 320, 264, 312,  28, 284, 456,  76, 271, 485,
       245,  33, 373,  44,   9, 371,  75,  38, 134, 169, 186, 305, 216,
       471,  43,  78, 273, 470,  83, 154, 472, 173,  37,  70, 121, 201,
       333, 332, 199, 414, 462, 366, 301, 109, 223, 290, 326, 140, 447,
       274, 272, 170, 264, 364,  10, 367, 256, 343, 426, 313, 49

In [81]:
arr2 = arr[arr <= 100]   ## np.where() 
arr2 

array([26, 55, 69, 61, 95, 96, 11, 39, 13, 25, 90, 31, 75, 76, 63, 27, 17,
       62, 93, 91,  9, 76, 80, 28, 76, 33, 44,  9, 75, 38, 43, 78, 83, 37,
       70, 10, 53, 63, 82, 90, 25, 73, 35])

In [83]:
arr2.size  


43

In [86]:
# 5,4  random array with filling 1 , 50 value    
arr = np.random.randint(1,50,(5,3))
arr 

array([[42, 31, 12],
       [ 6, 47, 48],
       [46, 30, 15],
       [42, 46, 17],
       [18, 10, 36]])

In [89]:
arr.ravel()  # to convert into 1D array  

array([42, 31, 12,  6, 47, 48, 46, 30, 15, 42, 46, 17, 18, 10, 36])

In [91]:
arr.flatten() # to convert into 1D array  


array([42, 31, 12,  6, 47, 48, 46, 30, 15, 42, 46, 17, 18, 10, 36])

In [93]:
arr.shape 

(5, 3)

In [95]:
arr 

array([[42, 31, 12],
       [ 6, 47, 48],
       [46, 30, 15],
       [42, 46, 17],
       [18, 10, 36]])

In [94]:
np.transpose(arr) 

array([[42,  6, 46, 42, 18],
       [31, 47, 30, 46, 10],
       [12, 48, 15, 17, 36]])

In [96]:
np.transpose(arr).shape 


(3, 5)

In [98]:
arr.T 

array([[42,  6, 46, 42, 18],
       [31, 47, 30, 46, 10],
       [12, 48, 15, 17, 36]])

In [106]:
arr = np.random.randint(1,200,20)
arr 

array([101, 186, 174,  51, 150, 179,  69, 117,   9, 173, 193,  11, 195,
        21,  98, 148,  21, 179,  75,  65])

In [103]:
# aggregate function  
print(arr.min()) 
print(arr.max()) 
print(arr.sum()) 
print(arr.mean())    # average  

5
190
2011
100.55


In [109]:
arr 

array([101, 186, 174,  51, 150, 179,  69, 117,   9, 173, 193,  11, 195,
        21,  98, 148,  21, 179,  75,  65])

In [107]:
np.argmin(arr)   # min() 

8

In [108]:
arr.min() 

9

In [110]:
np.argmax(arr)   # min() 

12

In [111]:
arr.max()

195

In [112]:
arr[12]

195

In [114]:
arr = np.array([8,7,9])
arr 

array([8, 7, 9])

In [115]:
arr.sort()

In [116]:
arr   # ascending 

array([7, 8, 9])

In [117]:
arr[::-1]  # descending order  

array([9, 8, 7])

In [118]:
arr = np.array([8,7,9])
arr 

array([8, 7, 9])

In [119]:
arr.argsort() 

array([1, 0, 2], dtype=int64)

In [ ]:
# [7,8,9]   

In [121]:
arr  + 5 

array([13, 12, 14])